language: go

services:
  - docker

before_install:
  - docker build --no-cache -t mauricethomas/osquery:${TRAVIS_COMMIT} .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mauricethomas/osquery:${TRAVIS_COMMIT}
  - docker tag mauricethomas/osquery:${TRAVIS_COMMIT} mauricethomas/osquery:latest
  - docker push mauricethomas/osquery:latest
